/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

typedef volatile unsigned int vuint32;

// GPIO
#define GPIOA_BASE 0x40010800
#define GPIOA_CRL (*(vuint32 *)(GPIOA_BASE + 0x00))
#define GPIOA_CRH (*(vuint32 *)(GPIOA_BASE + 0x04))
#define GPIOA_ODR (*(vuint32 *)(GPIOA_BASE + 0x0C))

// GPIOA_CRL pins
#define CNF0 2 // Configuration bit for pin 0

// GPIOA_CRH pins
#define MODE13 20 // Mode of Pin 13

// GPIOA_ODR pins
#define ODR13 13 // Position of pin 13
//--------------------------------------------------

// RCC
#define RCC_BASE 0x40021000
#define RCC_APB2ENR (*(vuint32 *)(RCC_BASE + 0x18))

// RCC_APB2ENR pins
#define IOPAEN 2 // Enable PortA pin
//--------------------------------------------------

// EXTI
#define EXTI_BASE	0x40010400
#define EXTI_IMR 	(*(vuint32 *)(EXTI_BASE + 0x00))
#define EXTI_RTSR 	(*(vuint32 *)(EXTI_BASE + 0x08))
#define EXTI_PR		(*(vuint32 *)(EXTI_BASE + 0x14))

// EXTI_IMR pins
#define MR0 0 // Unmask interrupt for external interrupt line 0

// EXTI_RTSR pins
#define TR0 0 // Enable rising edge trigger for external interrupt line 0

// EXTI_PR pins
#define PR0 0 // Pending trigger request for line 0


//--------------------------------------------------

// NVIC
#define NVIC_BASE	0xE000E100
#define NVIC_ISER0	(*(vuint32 *)(NVIC_BASE + 0x00))

// NVIC_ISER0 pins
#define SETENA6 6 // Irq for external interrupt line 0

//--------------------------------------------------


// Prototypes
void hardware_init(void);
void GPIO_init(void);
void EXTI_init(void);
void clock_init(void);

//--------------------------------------------------

int main(void)
{
	// Clock for GPIOA + GPIOA + EXTI + NVIC
	hardware_init();

	// Stay here forever
	while(1);

	return 0;
}

void EXTI0_IRQHandler(void)
{
	// Toggle state for GPIO PortA pin13
	GPIOA_ODR ^= (1 << ODR13);

	// Clear pending interrupt request
	EXTI_PR |= (1 << PR0);
}

void hardware_init(void)
{
	clock_init();
	GPIO_init();
	EXTI_init();
}

void GPIO_init(void)
{
	// GPIOA settings
	// Pin 0
	// Mode: Input Mode
	// Configuration: Floating Input
	GPIOA_CRL |= (1 << CNF0);

	// Pin 13
	// Mode: Output Mode, max speed = 2 MHz
	// Configuration: Open Drain
	GPIOA_CRH &= ~(0xF << MODE13);
	GPIOA_CRH |= (0x2 << MODE13);
}

void EXTI_init(void)
{
	// Configure the mask bits for interrupt line
	// Un-masking interrupt line 0
	EXTI_IMR |= (1 << MR0);

	// Configure the trigger selection bits
	// Enable rising trigger for line 0
	EXTI_RTSR |= (1 << TR0);

	// Configure the enable and mask bits that control the
	// NVIC IRQ channel mapped to the external interrupt controller
	NVIC_ISER0 |= (1 << SETENA6);
}

void clock_init(void)
{
	// Enable clock for IO PortA
	RCC_APB2ENR |= (1 << IOPAEN);
}
