/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "hw_access.h"

#define RCC_BASE 0x40021000
#define RCC_APB2ENR IO_RW_REG32(RCC_BASE + 0x18)
#define IOPAEN 2

#define GPIOA_BASE 0x40010800
#define GPIOA_CRH IO_RW_REG32(GPIOA_BASE + 0x04)
#define GPIOA_ODR IO_RW_REG32(GPIOA_BASE + 0x0C)
#define ODR13 13 // Position of pin 13
#define MODE13 20 // Mode of Pin 13


int main(void)
{
	uint32 i;
	RCC_APB2ENR |= (1 << IOPAEN);
	GPIOA_CRH &= ~(0xF << MODE13);
	GPIOA_CRH |= (0x2 << MODE13);

	while(1)
	{
		GPIOA_ODR |= (1 << ODR13);
		for(i = 0; i < 100000; i++);
		GPIOA_ODR &= ~(1 << ODR13);
		for(i = 0; i < 100000; i++);
	}

	return 0;
}
